server:
  port: 5001


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
spring:
  application:
    name: zuul5001

zuul:
  routes:
    order-server: /order-service/**
    products-server: /products-service/**